defaults: &defaults
  bucket: 'radiheyrails-development'
  access_key_id: 'AKIAIAHE5XZALNS3NPNQ'
  secret_access_key: '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'

development:
  <<: *defaults

production:
  <<: *defaults
  bucket: 'radiheyrails'
